# Usa la imagen oficial de MySQL
FROM mysql:latest

# Establece las variables de entorno
ENV MYSQL_DATABASE=admin
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin
ENV MYSQL_ROOT_PASSWORD=admin

# Copia cualquier archivo adicional o configuración si es necesario (opcional)
# COPY ./my.cnf /etc/mysql/my.cnf

# Exponer el puerto 3306 (el puerto interno de MySQL)
EXPOSE 3306
