/**
 * @author kalebsampaco
 * @description
 * Roles que estan definidos en la base de datos tabla: roles y sirven para dar accesos a la url de crear, actualizar o eliminar
 * La funcion authMiddlewareRole incluye estos Roles
 */
export enum ACCESS_ROLES {
  SUPERADMIN = 1,

  USER_CIUDADANO = 2,
  USER_EMPRESA = 3,

  CLI_ADMIN = 4,
  CLI_DIRECTOR_GENERAL = 5,
  CLI_VENTANILLA_UNICA = 19,
  CLI_PLANIFICACION_AMBIENTAL = 20,
  CLI_LIQUIDADOR = 21,
  CLI_FINANCIERO = 22,

  CLI_JURIDICO = 23,
  CLI_COORDINADOR_JURIDICO = 24,
  CLI_SUBDIRECTOR_JURIDICO = 25,
  CLI_JEFE_TERRITORIAL = 26,
  CLI_COORDINADOR_RECURSOS = 27,
  CLI_PROFESIONAL_RECURSOS = 28,
  CLI_SUBDIRECTOR_RECURSOS = 51,
  CLI_SECRETARIA_JURIDICA = 29,
  CLI_SUPERVISOR = 30,
  CLI_SUBDIRECTOR_ADMINISTRATIVO = 31,
  CLI_COORDINADOR_SEGUIMIENTO = 32,

  CLI_PROFESIONAL_SEGUIMIENTO = 33,
  CLI_VALIDACION_JURIDICA = 34,
  CLI_SUPERVISOR_SEGUIMIENTO = 35,
  CLI_VALIDACION_TECNICA = 38,

  CLI_COORDINADOR_RIESGO = 48,
  CLI_PROFESIONAL_RIESGO = 49,

  CLI_SECRETARIA_NUMERACION = 50,
  CLI_COORDINADOR_ADMINISTRATIVO = 53,
  CLI_PROFESIONAL_ATENCION = 54,

  CLI_VENTANILLA_DOCUMENTAL = 52,

  CLI_COORDINADOR_ADMINISTRATIVO_RECURSOS = 56,
  CLI_LIQUIDADOR_APROVECHAMIENTO = 57,

  CLI_CONTROL_TERMINOS = 61,
  CLI_APOYO_ADMINISTRATIVO_CONTROL = 60,
  CLI_APOYO_ADMINISTRATIVO = 58,
}
